server:
  port: 8081
  servlet.context-path: /user-api
  error.include-stacktrace: never

spring:
  application.name: user-service
  h2.console.enabled: true
  jpa.show-sql: true

#actuator configs
management:
  endpoints:
    enabled-by-default: true
    web.exposue: health

#swagger configs
#configure the path for swagger ui html. Default is /swagger-ui.html
#configured to default context path
springdoc:
  show-actuator: true
  packagesToScan: in.hp.java.userservice
  pathsToMatch: /users/**
  swagger-ui:
    enabled: true
    path: /
  api-docs:
    enabled: true
    path: /docs

#swagger ui properties
swagger-custom:
  name: User API
  version: '@project.version@' #this will be coming from pom
  description: '@project.description@'
  contact:
    name: Hariprasath
    url: https://github.com/hariprasath-r