server:
  port: 8081
  servlet.context-path: /user-api
  error.include-stacktrace: never

spring:
  application.name: user-service
  h2.console.enabled: true
  jpa.show-sql: true

#actuator configs
management:
  endpoints:
    enabled-by-default: true
    web.exposue: health
